// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Saakh.Api.Data;

#nullable disable

namespace Saakh.Api.Data.Migrations
{
    [DbContext(typeof(SaakhDbContext))]
    partial class SaakhDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Saakh.Api.Domain.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Saakh.Api.Domain.AdminActionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("SuspensionDuration")
                        .HasColumnType("int");

                    b.Property<Guid>("TargetProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("TargetProfileId", "OccurredAt");

                    b.ToTable("AdminActionLogs");
                });

            modelBuilder.Entity("Saakh.Api.Domain.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Saakh.Api.Domain.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("PhoneVerified")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Saakh.Api.Domain.CategorySubType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("DefaultUnit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("CategorySubTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            DefaultUnit = "INR",
                            DisplayName = "Working capital",
                            Key = "working-capital",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            DefaultUnit = "INR",
                            DisplayName = "Short-term advance",
                            Key = "short-term-advance",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            DefaultUnit = "INR",
                            DisplayName = "Stock credit line",
                            Key = "stock-credit",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 10,
                            Category = 2,
                            DefaultUnit = "kg",
                            DisplayName = "Fruits",
                            Key = "fruits",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 11,
                            Category = 2,
                            DefaultUnit = "litres",
                            DisplayName = "Dairy",
                            Key = "dairy",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 12,
                            Category = 2,
                            DefaultUnit = "units",
                            DisplayName = "Medicine",
                            Key = "medicine",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = 13,
                            Category = 2,
                            DefaultUnit = "units",
                            DisplayName = "Industrial equipment",
                            Key = "industrial-equipment",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = 14,
                            Category = 2,
                            DefaultUnit = "quintal",
                            DisplayName = "Grains & pulses",
                            Key = "grains-pulses",
                            SortOrder = 14
                        },
                        new
                        {
                            Id = 15,
                            Category = 2,
                            DefaultUnit = "metres",
                            DisplayName = "Textiles",
                            Key = "textiles",
                            SortOrder = 15
                        });
                });

            modelBuilder.Entity("Saakh.Api.Domain.Deal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Capacity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CapacityUnit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int?>("CategorySubTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("EstimatedSettlementTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("HaltedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("HaltedByProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InterestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("LenderConfirmedSettlement")
                        .HasColumnType("bit");

                    b.Property<Guid>("LenderProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LocationState")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaterialDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("SeekerConfirmedSettlement")
                        .HasColumnType("bit");

                    b.Property<Guid>("SeekerProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasColumnName("DealState");

                    b.HasKey("Id");

                    b.HasIndex("CategorySubTypeId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("HaltedByProfileId");

                    b.HasIndex("InterestId");

                    b.HasIndex("LenderProfileId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("SeekerProfileId");

                    b.HasIndex("State");

                    b.ToTable("Deals");
                });

            modelBuilder.Entity("Saakh.Api.Domain.DealStateHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("FromState")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ToState")
                        .HasColumnType("int");

                    b.Property<Guid?>("TriggeredByProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TriggeredByProfileId");

                    b.HasIndex("DealId", "OccurredAt");

                    b.ToTable("DealStateHistories");
                });

            modelBuilder.Entity("Saakh.Api.Domain.EvidenceDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ReviewedByAdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedByAdminId");

                    b.HasIndex("ProfileId", "SubmittedAt");

                    b.ToTable("EvidenceDocuments");
                });

            modelBuilder.Entity("Saakh.Api.Domain.Interest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FromProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("ToProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ToProfileId");

                    b.HasIndex("FromProfileId", "ToProfileId")
                        .IsUnique();

                    b.ToTable("Interests");
                });

            modelBuilder.Entity("Saakh.Api.Domain.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid?>("DealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InterestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SenderProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("SenderProfileId");

                    b.HasIndex("DealId", "SentAt");

                    b.HasIndex("InterestId", "SentAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Saakh.Api.Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Link")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "IsRead", "CreatedAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Saakh.Api.Domain.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailabilityStatus")
                        .HasColumnType("int");

                    b.Property<int>("BusinessSize")
                        .HasColumnType("int");

                    b.Property<decimal>("CapacityMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CapacityMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CapacityUnit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int?>("CategorySubTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gstin")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("GstinLegalName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("GstinVerifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsBusiness")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnTradeDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("SuspensionEndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategorySubTypeId");

                    b.HasIndex("Gstin");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("State", "District");

                    b.HasIndex("Role", "VerificationStatus", "AvailabilityStatus");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Saakh.Api.Domain.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RatedProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RaterProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RatedProfileId");

                    b.HasIndex("RaterProfileId");

                    b.HasIndex("DealId", "RaterProfileId")
                        .IsUnique();

                    b.ToTable("Ratings", t =>
                        {
                            t.HasCheckConstraint("CK_Rating_Stars", "[Stars] >= 1 AND [Stars] <= 5");
                        });
                });

            modelBuilder.Entity("Saakh.Api.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Saakh.Api.Domain.ResumeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestedByProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByProfileId");

                    b.HasIndex("DealId", "Status");

                    b.ToTable("ResumeRequests");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Saakh.Api.Domain.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Saakh.Api.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Saakh.Api.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Saakh.Api.Domain.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Saakh.Api.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Saakh.Api.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Saakh.Api.Domain.Admin", b =>
                {
                    b.HasOne("Saakh.Api.Domain.AppUser", "User")
                        .WithOne("Admin")
                        .HasForeignKey("Saakh.Api.Domain.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Saakh.Api.Domain.AdminActionLog", b =>
                {
                    b.HasOne("Saakh.Api.Domain.Admin", "Admin")
                        .WithMany("Actions")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Saakh.Api.Domain.Profile", "TargetProfile")
                        .WithMany()
                        .HasForeignKey("TargetProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("TargetProfile");
                });

            modelBuilder.Entity("Saakh.Api.Domain.Deal", b =>
                {
                    b.HasOne("Saakh.Api.Domain.CategorySubType", "CategorySubType")
                        .WithMany()
                        .HasForeignKey("CategorySubTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Saakh.Api.Domain.Profile", "HaltedByProfile")
                        .WithMany()
                        .HasForeignKey("HaltedByProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Saakh.Api.Domain.Interest", "Interest")
                        .WithMany("Deals")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Saakh.Api.Domain.Profile", "LenderProfile")
                        .WithMany("LenderDeals")
                        .HasForeignKey("LenderProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Saakh.Api.Domain.Profile", "SeekerProfile")
                        .WithMany("SeekerDeals")
                        .HasForeignKey("SeekerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategorySubType");

                    b.Navigation("HaltedByProfile");

                    b.Navigation("Interest");

                    b.Navigation("LenderProfile");

                    b.Navigation("SeekerProfile");
                });

            modelBuilder.Entity("Saakh.Api.Domain.DealStateHistory", b =>
                {
                    b.HasOne("Saakh.Api.Domain.Deal", "Deal")
                        .WithMany("StateHistory")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Saakh.Api.Domain.Profile", "TriggeredByProfile")
                        .WithMany()
                        .HasForeignKey("TriggeredByProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Deal");

                    b.Navigation("TriggeredByProfile");
                });

            modelBuilder.Entity("Saakh.Api.Domain.EvidenceDocument", b =>
                {
                    b.HasOne("Saakh.Api.Domain.Profile", "Profile")
                        .WithMany("EvidenceDocuments")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Saakh.Api.Domain.Admin", "ReviewedByAdmin")
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Profile");

                    b.Navigation("ReviewedByAdmin");
                });

            modelBuilder.Entity("Saakh.Api.Domain.Interest", b =>
                {
                    b.HasOne("Saakh.Api.Domain.Profile", "FromProfile")
                        .WithMany("SentInterests")
                        .HasForeignKey("FromProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Saakh.Api.Domain.Profile", "ToProfile")
                        .WithMany("ReceivedInterests")
                        .HasForeignKey("ToProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromProfile");

                    b.Navigation("ToProfile");
                });

            modelBuilder.Entity("Saakh.Api.Domain.Message", b =>
                {
                    b.HasOne("Saakh.Api.Domain.Deal", "Deal")
                        .WithMany("Messages")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Saakh.Api.Domain.Interest", "Interest")
                        .WithMany("Messages")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Saakh.Api.Domain.Profile", "SenderProfile")
                        .WithMany()
                        .HasForeignKey("SenderProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Deal");

                    b.Navigation("Interest");

                    b.Navigation("SenderProfile");
                });

            modelBuilder.Entity("Saakh.Api.Domain.Notification", b =>
                {
                    b.HasOne("Saakh.Api.Domain.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Saakh.Api.Domain.Profile", b =>
                {
                    b.HasOne("Saakh.Api.Domain.CategorySubType", "CategorySubType")
                        .WithMany()
                        .HasForeignKey("CategorySubTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Saakh.Api.Domain.AppUser", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Saakh.Api.Domain.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategorySubType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Saakh.Api.Domain.Rating", b =>
                {
                    b.HasOne("Saakh.Api.Domain.Deal", "Deal")
                        .WithMany("Ratings")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Saakh.Api.Domain.Profile", "RatedProfile")
                        .WithMany("RatingsReceived")
                        .HasForeignKey("RatedProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Saakh.Api.Domain.Profile", "RaterProfile")
                        .WithMany("RatingsGiven")
                        .HasForeignKey("RaterProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Deal");

                    b.Navigation("RatedProfile");

                    b.Navigation("RaterProfile");
                });

            modelBuilder.Entity("Saakh.Api.Domain.RefreshToken", b =>
                {
                    b.HasOne("Saakh.Api.Domain.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Saakh.Api.Domain.ResumeRequest", b =>
                {
                    b.HasOne("Saakh.Api.Domain.Deal", "Deal")
                        .WithMany("ResumeRequests")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Saakh.Api.Domain.Profile", "RequestedByProfile")
                        .WithMany()
                        .HasForeignKey("RequestedByProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Deal");

                    b.Navigation("RequestedByProfile");
                });

            modelBuilder.Entity("Saakh.Api.Domain.Admin", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("Saakh.Api.Domain.AppUser", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Profile");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Saakh.Api.Domain.Deal", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Ratings");

                    b.Navigation("ResumeRequests");

                    b.Navigation("StateHistory");
                });

            modelBuilder.Entity("Saakh.Api.Domain.Interest", b =>
                {
                    b.Navigation("Deals");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Saakh.Api.Domain.Profile", b =>
                {
                    b.Navigation("EvidenceDocuments");

                    b.Navigation("LenderDeals");

                    b.Navigation("RatingsGiven");

                    b.Navigation("RatingsReceived");

                    b.Navigation("ReceivedInterests");

                    b.Navigation("SeekerDeals");

                    b.Navigation("SentInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
